// Roboto Regular TTF (latin-ext) base64, imported as raw text to keep TS lean
// Generated via:
// curl -L https://github.com/google/fonts/raw/main/apache/roboto/Roboto-Regular.ttf | base64 -w0 > roboto-regular-base64.txt
import fontBase64 from './roboto-regular-base64.txt?raw';

export const ROBOTO_TTF_BASE64 = fontBase64.trim();
// Roboto Regular (latin-ext) as base64 for jsPDF embedding
// Source: https://fonts.gstatic.com/s/roboto/v30/KFOmCnqEu92Fr1Mu72xKOzY.woff
export const ROBOTO_BASE64 =
  'd09GRgABAAAAAAawABMAAAAAC9QAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAABPUy8yAAABCAAAAGAAAABgDxIPd2NtYXAAAAGIAAAAOgAAADoK1zKpZ2FzcAAAAdAAAAA0AAAANAAAABBuZWFkAAAB3AAAADMAAAA0AFwAB2hlYWQAAAH8AAAANAAAADQAFgAMaG10eAAAAgQAAACkAAAApAOcBKBobXR4AAACIwAAABYAAAAWAgYAZ2x5ZgAAAjwAAAJkAAACZKMe0rRoZWFkAAAEKAAAAC0AAAAuHdwZQWhoZWEAAARYAAAAIAAAACAA6QEJaG10eAAABHgAAAAgAAAAIAEaAA9sb2NhAAAEoAAAABgAAAAYAIIADm1heHAAAAS8AAAAGAAAAEAAEAAbbmFtZQAABOQAAAEfAAABHwZkLfxwb3N0AAAFiAAAADoAAAA6HhYAYnByZXAAAAVsAAAAIAAAACAAAwAAeJxjYGRgYOBiMGCwY2BycfMJYeDlYGQAg4EJAZhpgJIMh8P8zA0A0P9a9lZJzMvBzEwsgwAgwQYGAWIS4Z7APe8AxhAn8QfCxh+NLwDDk2AKEQeIS0Ax1cGgB4nGNgYGBmgGAZBkYGEJwB4nKNgZGBg4GIwYLBjYHJx8wlh4OVgZACDgQkBmGiACSzAu/v///w8g0GtHAwD9xgpR';

